name = "nvidia-nim-chat-site"
compatibility_date = "2026-05-21"
pages_build_output_dir = "public"

[vars]
NVIDIA_BASE_URL = "https://integrate.api.nvidia.com/v1"
NVIDIA_MODEL = "openai/gpt-oss-120b"

[[kv_namespaces]]
binding = "CHAT_KV"
id = "ca5f55ca7b5a4211a3a6e03513555e5c"
